### ISSUE TITLE
Behaviour flags

### ISSUE THREAD

**Issue by half-cambodian-hacker-man** [SerenityEnterprises/paramorphism-issues#7]
We can do a lot more obfuscation when we know that something isn't going to happen in the program. For instance, self-ASM or reflection.

The config should look like this, but all flags should default to `false`:

```yml
flags:
  no_asm: true
  no_bcel: true
  no_reflection: true
```

If we know that there's absolutely no ASM or BCEL, we can do some tricks that crash the libraries themselves, rendering most analysis tools unusable.
